site_name: База знаний
site_url: https://wiki.dyussenov.dev/
site_description: Справочник по программированию
site_author: Асет Дюсенов
copyright: 2020-2023, Асет Дюсенов

# Repository
repo_name: dyussenov/python-course
repo_url: https://github.com/dyussenov/python-course


nav:
    - Старт: index.md
    - Python Core:
      - Способы создания переменных: basic/variables.md
      - Ввод и вывод данных. Функции print() и input(): basic/input.md
      - If, else, elif: basic/if.md
      - Цикл while: basic/while-python.md
      - Цикл for: basic/lesson5-for.md
      - Типы данных:
        - Типы данных: basic/datatypes/datatypes-intro.md
        - Строки: basic/datatypes/lesson6-strings.md
        - Списки: basic/datatypes/lesson4-lists.md
        - Генераторы списков: basic/datatypes/comprehensions.md
        - Кортежи: basic/datatypes/tuples.md
        - Словари: basic/datatypes/dict.md
        - Множества: basic/datatypes/set.md
        - Коллекции: basic/datatypes/collections.md
        - Срезы: basic/datatypes/lesson6-slices.md
        - Byte-строки: basic/datatypes/bytestring.md
      - Исключения. Try, except, finally: basic/exception.md
      - Аннотации типов: basic/typehints.md
      - Функции:
        - Создание функций: basic/functions/functions.md
        - args и kwargs: basic/functions/args.md
        - Рекурсия в функциях: basic/functions/recurtion.md
        - Анонимные функции: basic/functions/lambda.md
        - Декораторы: basic/functions/decorators.md
      - Файлы:
        - Открытие и чтение файлов: basic/text_files/files_read.md
        - Запись в файлы: basic/text_files/files_write.md
      - Assert: basic/assert.md
      - ООП:
        - Введение в ООП: basic/oop/intro.md
        - Классы, объекты, методы: basic/oop/create.md
        - Инкапсуляция: basic/oop/03_encapsulation.md
        - Наследование: basic/oop/04_inheritance.md
        - Полфиморфизм: basic/oop/05_polymorphism.md
    - Базы данных:
      - SQLite 3:
        - SQL и реляционные базы данных: db/sqlite/sql.md
        - DDL запросы. Создание, изменение, удаление таблиц: db/sqlite/01_ddl.md
        - Подключение к базе данных через Python: db/sqlite/02_connection.md
        - DML запросы. INSERT, UPDATE и DELETE: db/sqlite/03_dml.md
        - DQL запрос. SELECT: db/sqlite/04_dql.md
        - Функции агрегации и группировка: db/sqlite/05_agregation_grouping.md
        - Внешние ключи. Объединение таблиц: db/sqlite/06_foreign_key_join.md
        - Заключение: db/sqlite.md
      - Postgresql:
        - Запуск через docker контейнер: db/postgresql/install.md
    - Модули:
      - Datetime. Работа с временем и датой: modules/datetime.md
      - Json в Python: modules/json.md
      - Requests. Запросы: modules/requests.md
      - Faker. Генерация фейковых данных: modules/faker.md
      - Virtualenv. Создание виртуального окружения: modules/venv.md
      - Pathlib. Работа с путями: modules/pathlib.md
      - Pytest. Тестирование: modules/pytest.md
      - Flake8. Линтеры: modules/flake8.md
      - Prettytable. Красивые таблицы: modules/prettytable.md
    - WEB:
      - Протокол HTTP: web/http.md
      - Curl: web/curl.md
      - Makefile: web/makefile.md
    - Git:
      - Git в Windows: git/git_windows.md
      - Удаление файлов в репозитории: git/git_delete.md
    - Django:
      - Что такое Django?: django/intro.md
      - Создание проекта Django: django/init.md
      - Создание приложения в проекте: django/creating_app.md
      - Маршрутизация и шаблоны URL: django/routing.md
      - Переадресация и отправка статусных кодов: django/redirect_and_status.md
      - Создание моделей: django/creating_models.md
      - Модели с изображениями: django/image_model.md
      - Регистрация, аутентификация: django/auth.md
    - Aiogram:
      - Введение: aiogram/intro.md
      - Эхо-бот: aiogram/echo-bot.md
    - Orm:
      - SQLAlchemy:
        - Введение: orm/sqlalchemy/start.md
    - JavaScript:
      - Работа с DOM деревом: js/dom.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.svg
  language: ru
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    # - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.expand

use_directory_urls: true
markdown_extensions:
  - attr_list
  - md_in_html
  - smarty
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: G-GPHQZETNLC

